## Section 13 — Handling Missing Values

In [49]:
import pandas as pd
import numpy as np
from google.colab import files
daya_up = files.upload()
df = pd.read_csv('Diabetes Missing Data.csv')

Saving Diabetes Missing Data.csv to Diabetes Missing Data.csv

In [50]:
df.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [51]:
df.shape

(768, 9)

In [52]:
print("Unique Values per Column:")
df.nunique()

Unique Values per Column:

Pregnant              17
Glucose              135
Diastolic_BP          46
Skin_Fold             50
Serum_Insulin        185
BMI                  247
Diabetes_Pedigree    517
Age                   52
Class                  2
dtype: int64

In [53]:
# TODO
# Find Missing Values of your Dataset
print("Missing values per column:")
df.isnull().sum()

Missing values per column:

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [ ]:
# Identify which way you should impute those missing values
# Apply the methods to impute missing values

## Section 14 — Encoding Categorical Variables

In [54]:
# TODO
# Identify categorical features
# Take decision on what encoding will you apply for each categorical features
# Apply the methods to encode the features and show final data

## Section 15 — Normalization and Scaling

In [55]:
# TODO
# Check if your dataset have features with different range of values or not
# Take decision on whether scaling is required or not
# If required apply one of the scaling method